config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
  root to: "tasks#index"
  
  get "login", to: "session#new"
  post "login", to: "session#create"
  delete "logout", to: "session#destroy"
  
  get "signup", to: "users#new"
  resources :users, only:[:new, :create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  
  validates :content, presence: true, length: {maximum: 255}
  validates :status, presence: true, length: {maximum: 10}
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  
  has_secure_password
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @counts_tasks = user.tasks.group(:status).count
  end
    
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = "ログインに成功しました"
      redirect_to root_url
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました"
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :set_task, only: [:update, :destroy, :edit, :show]

  def new
    @task = Task.new
  end
  
  def index
    @tasks = current_user.tasks.order("created_at DESC").page(params[:page])
    counts(current_user)
  end

  def update

    if @task.update(task_params)
      flash[:success] = "編集が完了しました"
      redirect_to @task
    else
      flash.now[:danger] = "編集を完了できませんでした"
      render :edit      
    end
  end
  
  def destroy
    @task.destroy
    flash[:success] = "タスクを削除しました"
    redirect_to tasks_url
  end

  def create
    @task = current_user.tasks.build(task_params)
    
    if @task.save
      flash[:success] = "タスクを登録しました"
      redirect_to root_url
    else
      flash.now[:danger] = "タスクを登録できませんでした"
      render :new
    end
  end

  def edit
  end

  def show
  end

  private
  
  #Strong Parameter
  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  def set_task
    @task = current_user.tasks.find_by(id: params[:id])
    if !@task
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザ登録が完了しました"
      redirect_to root_url
      #仮のリダイレクト
    else
      flash.now[:danger] = "ユーザ登録に失敗しました"
      render :new
    end
      
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all.page(params[:page])
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>

<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Tasklist</a>
    </div>
    
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li class=""><%= link_to "タスクを登録", new_task_path %></li>
        <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
        <span class="navbar-text">ログイン中のユーザ：<%= current_user.name %> (id:<%= current_user.id %>)</span>
        <% else %>
        <li><%= link_to "ユーザ登録", signup_path %></li>
        <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
      <ul
    </div>
  </div>
</nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Tasklist</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <div class="container">
      <%= render "layouts/navbar" %>
      <%= render "layouts/flash_messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/session/new.html.erb
<div class="text-center">
  <h1>ログイン</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>
    <div class="form-group">
      <%= f.label :email, "メールアドレス" %>
      <%= f.text_field :email, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
    
      <%= f.submit "ログイン", class: "btn btn-primary btn-block" %>
    <% end %>
    
    <div>
      新規登録は<%= link_to "こちら", signup_path %>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2 col-lg-6 col-lg-offset-3">

<%= form_for(task) do |f| %>
  <% if task.errors.any? %>
    <ul class="alert alert-warning">
      <li>
        <% task.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      </li>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :content, "タスク", class: "control-label" %> 
    <%= f.text_field :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :status, "状態", class: "control-label" %> 
    <%= f.select :status, ["未処理", "保留中", "完了済"], {}, class: "form-control" %>
  </div>
  
    <%= f.submit "タスクを登録する", class: "btn btn-primary btn-block" %>

<% end %>

  </div>
</div>

app/views/tasks/edit.html.erb
<h1>タスクを編集する</h1>

<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<div class="text-center">
  <h1>タスク一覧</h1>
</div>

<div class="alt-table-responsive">
  
<table class="table">
  <tr>
    <th>作成日時</th>
    <th>タスク（未処理：<%= @counts_tasks["未処理"] %>件、保留中：<%= @counts_tasks["保留中"] %>件）</th>
    <th>状態</th>
  </tr>
    <% @tasks.each do |task| %>
    <tr>
      <td><%= link_to task.created_at.to_s, task %></td>
      <td><%= task.content %></td>
      <td><%= task.status %></td>
    </tr>
    <% end %>
</table>

  <%= paginate @tasks %>

  <%= link_to "タスクを登録", new_task_path, class:"btn btn-primary" %>    

</div>    

app/views/tasks/new.html.erb
<div class="text-center">
  <h1>新規タスクを追加</h1>
</div>

<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1>タスク詳細</h1>

<p>タスク：<%= @task.content %>【<%= @task.status %>】</p>

<%= link_to "編集", edit_task_path(@task), class: "btn btn-success" %>
<%= link_to "削除", @task, method: :DELETE ,data: { confirm: "本当に削除してよろしいですか"}, class: "btn btn-danger" %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <%= users.each do |user| %>
    <li class="media">
      <div "media-left">
        <img class="media-object img-rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt=""> 
      </div>
      <div class="media-body">
        <div>
          <%= user.name %>
        </div>
        <div>
          <p><%= link_to "ユーザの詳細", user %></p>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/index.html.erb
<div class="text-center">
  <h1>ユーザ一覧</h1>
</div>

<%= render "users", users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>新規ユーザ登録</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <% if @user.errors.any? %>
      <ul class="alert alert-warning">
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    
    <%= form_for (@user) do |f| %>
    
      <div class="form-group">
        <%= f.label :name, "ユーザ名" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, "メールアドレス" %>
        <%= f.text_field :email, class: "form-control" %>
      </div>
        
      <div class="form-group">
        <%= f.label :password, "パスワード" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
        
      <div class="form-group">
        <%= f.label :password_confirmation, "パスワード（確認用）" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
        
      <%= f.submit "ユーザ登録", class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="text-center">
  <h1>ユーザ名：<%= @user.name %></h1>
</div> 